# Generated by Django 5.2.4 on 2025-07-13 18:02

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VaultItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Descriptive title for the vault item', max_length=255)),
                ('encrypted_data', models.TextField(help_text='Base64 encoded encrypted string')),
                ('encryption_algorithm', models.CharField(default='AES-256-CBC', help_text='Algorithm used for encryption', max_length=50)),
                ('item_type', models.CharField(choices=[('password', 'Password'), ('note', 'Secure Note'), ('other', 'Other')], default='password', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description for the vault item')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When the item was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the item was last updated')),
                ('last_accessed', models.DateTimeField(blank=True, help_text='When the item was last accessed', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the item expires (optional)', null=True)),
                ('soft_deleted', models.BooleanField(default=False, help_text='Soft delete flag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vault Item',
                'verbose_name_plural': 'Vault Items',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VaultItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Action performed on the item', max_length=50)),
                ('details', models.JSONField(blank=True, help_text='Additional details about the action', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vault_item_history', to=settings.AUTH_USER_MODEL)),
                ('vault_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='vault.vaultitem')),
            ],
            options={
                'verbose_name': 'Vault Item History',
                'verbose_name_plural': 'Vault Item Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='vaultitem',
            index=models.Index(fields=['user', 'soft_deleted'], name='vault_vault_user_id_e27bd9_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultitem',
            index=models.Index(fields=['user', 'item_type'], name='vault_vault_user_id_c5e6a8_idx'),
        ),
        migrations.AddIndex(
            model_name='vaultitem',
            index=models.Index(fields=['user', 'created_at'], name='vault_vault_user_id_e6bf4d_idx'),
        ),
    ]
