# Generated by Django 5.2.4 on 2025-07-31 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_mfa_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mfa_secret',
        ),
    ]
