# Generated by Django 5.2.4 on 2025-08-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mfa_sms_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sms_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
