# Generated by Django 5.2.4 on 2025-08-04 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_mfa_sms_enabled_userprofile_sms_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
