# Generated by Django 5.2.4 on 2025-08-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_totp_enabled_userprofile_totp_secret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='totp_secret',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
